# Generated by Django 4.0.6 on 2022-07-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='botusers',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botusers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='botusers',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
